apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: spraguesy.io
  dnsNames:
    - fib.spraguesy.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fib.spraguesy.io 